class_name GameConstants
extends RefCounted

const PIXELS_PER_METER := 20.0
const METERS_PER_PIXEL := 0.05
const PATH_MIN_STEP_LENGTH := 0.01

const TANK_WIDTH := 60.0
const TANK_HEIGHT := 80.0
const TANK_ROTATION_SPEED := 5.0
const TANK_FORWARD_SPEED := 319.0
const TANK_BACK_SPEED := 256.0

const BULLET_RADIUS := 5.0
const BULLET_SPEED := 360.0
const BULLET_OFFSET := 50.0
const BULLET_AMMO_COUNT := 5
const BULLET_MAX_LIFETIME := 10.0

const LASER_SPEED := 3600.0
const LASER_OFFSET := 50.0
const LASER_LOCK_TIME := 0.2
const LASER_MAX_LIFETIME := 0.8

const DOUBLE_BARREL_RADIUS := 5.0
const DOUBLE_BARREL_SPEED := 360.0
const DOUBLE_BARREL_OFFSET := 45.0
const DOUBLE_BARREL_SPACE := 9.0
const DOUBLE_BARREL_AMMO_COUNT := 10
const DOUBLE_BARREL_MAX_LIFETIME := 6.0

const SHOTGUN_RADIUS := 2.0
const SHOTGUN_MIN_SPEED := 600.0
const SHOTGUN_MAX_SPEED := 700.0
const SHOTGUN_OFFSET := 49.0
const SHOTGUN_SPACE := 8.0
const SHOTGUN_AMMO_COUNT := 3
const SHOTGUN_NUM_BUCKSHOT := 20
const SHOTGUN_BUCKSHOT_SPREAD := 0.3
const SHOTGUN_RELOAD_TIME := 1.0
const SHOTGUN_LIFETIME_AFTER_MAZE_HIT := 0.7
const SHOTGUN_MAX_LIFETIME := 2.0

const HOMING_MISSILE_RADIUS := 4.0
const HOMING_MISSILE_SPEED := 360.0
const HOMING_MISSILE_OFFSET := 50.0
const HOMING_MISSILE_ACCELERATION := 40.0
const HOMING_MISSILE_ACTIVATION_TIME := 2.0
const HOMING_MISSILE_MAX_LIFETIME := 10.0

const MINE_RADIUS := 16.0
const MINE_LAUNCH_SPEED := 250.0
const MINE_MIN_SPEED := 500.0
const MINE_MAX_SPEED := 700.0
const MINE_OFFSET := -29.0
const MINE_ACCELERATION := 40.0
const MINE_AMMO_COUNT := 3
const MINE_ACTIVATION_DELAY := 0.5
const MINE_DETONATION_DELAY := 0.4
const MINE_NUM_SHRAPNEL := 30

const GATLING_GUN_RADIUS := 2.0
const GATLING_GUN_MIN_SPEED := 500.0
const GATLING_GUN_MAX_SPEED := 600.0
const GATLING_GUN_OFFSET := 60.0
const GATLING_GUN_SPACE := 8.0
const GATLING_GUN_AMMO_COUNT := 20
const GATLING_GUN_BULLET_SPREAD := 0.1
const GATLING_GUN_CHARGE_TIME := 0.5
const GATLING_GUN_FIRE_RATE := 0.12
const GATLING_GUN_DISCHARGE_TIME := 1.5
const GATLING_GUN_MAX_LIFETIME := 2.0

const CRATE_WIDTH := 64.0
const CRATE_HEIGHT := 64.0
const CRATE_SPAWN_DURATION_MIN := 3.0
const CRATE_SPAWN_DURATION_VARIANCE := 5.0
const CRATE_MINIMUM_TILES_TO_TANKS := 4
const MAX_CRATES := 3

const LASER_AIMER_LENGTH := 60.0
const SPAWN_SHIELD_LIFETIME := 10.0
const SPAWN_SHIELD_WEAKEN_TIME := 2.0
const AIMER_LENGTH := 60.0
const AIMER_LIFETIME := 10.0
const SHIELD_LIFETIME := 6.0
const SHIELD_WEAKEN_TIME := 2.0
const SPEED_BOOST_LIFETIME := 10.0
const SPEED_BOOST_EFFECT := 0.3

const CLASSIC_STORM_APPEAR_DURATION := 60.0
const DEATHMATCH_ROUND_DURATION := 60.0
const DEATHMATCH_RESPAWN_DURATION := 1.0
const DEATHMATCH_STORM_APPEAR_DURATION := 30.0
const BETWEEN_ROUNDS_DURATION := 1.0
const CELEBRATION_DURATION := 7.0
const COUNTDOWN_START_VALUE := 3
const COUNTDOWN_DURATION := 0.5
const ROUND_FINISHING_DURATION := 3.0
