extends SceneTree

const Store = preload("res://game/application/settings_store.gd")
const Migration = preload("res://game/application/settings_migration.gd")
const TEST_PATH := "res://.tmp/settings-test.json"

func _initialize(): call_deferred("_run")

func _write(payload):
	var file = FileAccess.open(TEST_PATH, FileAccess.WRITE)
	file.store_string(JSON.stringify(payload))
	file.close()

func _run():
	_write({"volume": 0.35, "quality": "LOW", "assignments": ["mouse", "mouse", "invalid", "arrowKeys"]})
	var store = Store.new(TEST_PATH)
	store.load_settings()
	assert(store.values == {"volume": 0.35, "quality": "low", "assignments": ["mouse", "arrowKeys"]})
	assert(store.save_settings())
	var persisted = JSON.parse_string(FileAccess.get_file_as_string(TEST_PATH))
	assert(persisted.schema_version == Migration.CURRENT_VERSION)
	var loaded = Store.new(TEST_PATH)
	loaded.load_settings()
	assert(loaded.values == store.values)
	store.set_volume(2.0)
	assert(store.values.volume == 1.0)
	store.set_volume(NAN)
	assert(store.values.volume == 1.0)
	store.set_quality("auto")
	assert(store.values.quality == "auto")
	store.set_quality("medium")
	assert(store.values.quality == "high")
	store.set_assignments(["mouse", "WASDKeys", "mouse", "arrowKeys", "unknown"])
	assert(store.values.assignments == ["mouse", "WASDKeys", "arrowKeys"])
	_write({"schema_version": 1, "values": {"volume": {}, "quality": [], "assignments": [null]}})
	assert(loaded.load_settings() == Migration.DEFAULTS)
	_write({"schema_version": 2, "values": {"future": true}})
	var future_contents = FileAccess.get_file_as_string(TEST_PATH)
	loaded.load_settings()
	assert(not loaded.save_settings())
	assert(FileAccess.get_file_as_string(TEST_PATH) == future_contents)
	var broken = FileAccess.open(TEST_PATH, FileAccess.WRITE)
	broken.store_string("{")
	broken.close()
	assert(loaded.load_settings() == Migration.DEFAULTS)
	assert(not loaded.save_settings())
	DirAccess.remove_absolute(TEST_PATH)
	var output = FileAccess.open("res://.tmp/settings-store.actual.json", FileAccess.WRITE)
	output.store_string(JSON.stringify({"migration": true, "validation": true, "future_preserved": true, "isolated": true}))
	quit(0)
